### ISSUE TITLE
Game crashes on an attempt to calculate gap size with non-existent spheres at the start of a path

### ISSUE THREAD

**Issue by FredZachary** [ZumaBlitzRemake/ZumaBlitzRemake#12]
https://user-images.githubusercontent.com/107924805/216813403-f1e99598-7507-4550-b1e2-04c98a028313.mp4

**Comment by ShamblesSM** [comment]
Managed to reproduce bug while I was using the turtle curve clear strat with Curvy Fries; issue has been fixed and closed.
