### ISSUE TITLE
Ball fired when pause button is clicked

### ISSUE THREAD

**Issue by bchantech** [ZumaBlitzRemake/ZumaBlitzRemake#18]
When the pause button is clicked on in game, a ball is fired, and then the game pauses when the mouse button is released.

**Comment by ShamblesSM** [comment]
Already filed this issue on the original repository (which was a fork of OpenSMCE but on my personal account) - but I forgot to move/duplicate it here. Keeping this issue.

As @jakubg1 said, there is a Y-offset of where balls are not allowed to shoot, and UI elements are not detected on click, thus allowing the player to click on a UI element and shoot at the same time.
